alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias ls="eza -l --icons --git --group-directories-first --time-style=relative"
alias rm="rm -i"
alias ssh_tunnel_bg="ssh -f -N"
alias sha256sum="shasum -a 256"
alias who8080="lsof -i tcp:8080"
alias getPID="ps -p"
alias unset="set --erase"
alias getSize="stat -f%z"
