# Kitty Quick Access Terminal

edge center-sized
lines 1000px
columns 1500px
background_opacity 0.90
kitty_override background_image_layout=cscaled
hide_on_focus_loss false 
app_id kitty-quick-access
